# ================================
# Worker образ PHP 8.3
# ================================
FROM php:8.3-fpm

# Рабочие директории
WORKDIR /

# ================================
# 1️⃣ Системные пакеты
# ================================
RUN apt-get update && apt-get install -y \
    mariadb-client \
    net-tools \
    iputils-ping \
    curl \
    unzip \
    iptables \
    grep \
    procps \
    libssh2-1-dev \
    redis-tools \
    supervisor \
    ca-certificates \
    openssl \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libwebp-dev \
    && rm -rf /var/lib/apt/lists/*

# ================================
# 2️⃣ PHP расширения и PECL
# ================================
RUN docker-php-ext-install pdo pcntl pdo_mysql \
    # Добавьте эту строку для установки GD
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install gd \
    && pecl install ssh2-1.3.1 redis \
    && docker-php-ext-enable ssh2 redis

# ================================
# 3️⃣ Установка Composer
# ================================
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && php -r "unlink('composer-setup.php');" \
    && composer --version

# ================================
# 4️⃣ Настройка Supervisor
# ================================
RUN mkdir -p /var/run/supervisor \
    && chown www-data:www-data /var/run/supervisor \
    && chmod 770 /var/run/supervisor

# ================================
# 5️⃣ Установка NVM и Node.js
# ================================
ENV NVM_DIR=/usr/local/nvm
ENV NODE_VERSION=22.15.0
RUN mkdir -p "$NVM_DIR" \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default
ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

# ================================
# 6️⃣ Laravel / рабочая директория
# ================================
WORKDIR /var/www/html
