# syntax=docker/dockerfile:1.4
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime as base

WORKDIR /app

# Установка системных зависимостей
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ffmpeg libsndfile1 espeak-ng sox \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Создаем директории
RUN mkdir -p /app/code /app/models/tts /app/storage /app/data

# Копируем requirements для кэширования
COPY configs/voicetts/requirements.txt .

# Устанавливаем зависимости с кэшированием
RUN pip install --no-cache-dir -r requirements.txt

# Настройка окружения
ENV TTS_HOME=/app/models/tts
ENV CUDA_VISIBLE_DEVICES=0
ENV PYTHONPATH=/app/code
ENV PATH=/opt/conda/bin:$PATH

EXPOSE 5001

# Код монтируется через volumes в docker-compose
#CMD ["python", "app.py"]