[unix_http_server]
file=/var/run/supervisor.sock  ; Изменили путь для простоты
chmod=0777

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid  ; Упрощенный путь
user=root
umask=000  ; Максимально разрешающие права

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:queue]
command=bash -c "set -a && . /var/www/html/.env && set +a && php /var/www/html/artisan queue:work --tries=3 --timeout=300"
user=www-data
stdout_logfile=/var/log/worker/queue.out.log
stderr_logfile=/var/log/worker/queue.err.log

[program:scheduler]
command=bash -c "set -a && . /var/www/html/.env && set +a && while true; do php /var/www/html/artisan schedule:run --no-interaction; sleep 10; done"
user=www-data
stdout_logfile=/var/log/worker/scheduler.out.log
stderr_logfile=/var/log/worker/scheduler.err.log
autostart=true
autorestart=true

[program:telegram-updates]
command=bash -c "set -a && . /var/www/html/.env && set +a && php /var/www/html/artisan command:TGgetUpdates"
autostart=true
autorestart=true
user=www-data
stdout_logfile=/var/log/worker/telegram-updates.log

[program:vk-updates]
command=bash -c "set -a && . /var/www/html/.env && set +a && php /var/www/html/artisan command:VKgetUpdates"
autostart=true
autorestart=true
user=www-data
stdout_logfile=/var/log/worker/vk-updates.log

# Новый сервис для отправки логов
#[program:log-sender]
#command=/usr/local/bin/log-sender.sh
#autostart=true
#autorestart=false
#startsecs=0
#startretries=0
#user=root
#stdout_logfile=/var/log/worker/log-sender.out.log
#stderr_logfile=/var/log/worker/log-sender.err.log

# UPDATE VPN IP
# [program:vpn-ip-update]
# command=/usr/local/bin/vpn-ip-update.sh
# autostart=true
# autorestart=unexpected
# startsecs=10
# startretries=5
# restartsecs=60
# exitcodes=0,1
# user=root
# stdout_logfile=/var/log/worker/vpn-ip-update.out.log
# stderr_logfile=/var/log/worker/vpn-ip-update.err.log